version: "3"

networks:
  redis-net: {}

volumes:
  redis-vol: {}

services:
  redis:
    image: redis:alpine
    networks:
      - redis-net
    restart: unless-stopped
    volumes:
      - redis-vol:/data
    healthcheck:
      test: redis-cli -h redis -p 6379 ping
      start_period: 3s
      interval: 2s
      timeout: 2s
      retries: 10

  laravel-echo-server:
    image: oanhnn/laravel-echo-server:latest
    depends_on:
      - redis
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: http://example.com
      LARAVEL_ECHO_SERVER_DEBUG:     'true'
      LARAVEL_ECHO_SERVER_DB:        redis
      REDIS_HOST:     redis
      REDIS_PORT:     6379
      REDIS_PREFIX:   ""
      REDIS_DB:       0
    networks:
      - redis-net
    ports:
     - 6001:6001
    restart: unless-stopped
    healthcheck:
      test: node /usr/local/src/healthcheck.js
      start_period: 5s
      interval: 3s
      timeout: 3s
      retries: 10
